### ISSUE TITLE
Change the app name to stonks

### ISSUE THREAD

**Issue by aucls** [AugustoDeveloper/stock-tracer-app#1]

**Comment by aucls** [comment]
Just do it

**Comment by AugustoDeveloper** [comment]
![images (10).jpeg](https://user-images.githubusercontent.com/4335700/109893376-5044dd00-7c6a-11eb-924d-afc33c4a4dfd.jpeg)

**Comment by AugustoDeveloper** [comment]
Done.
App release at: 
https://stonks-tracer-app.herokuapp.com
